language: python
python:
  - "2.7"
sudo: required
dist: trusty
addons:
  postgresql: "9.4"
services:
  - postgresql
virtualenv:
  system_site_packages: true
# install prerequisites
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-numpy python-scipy libgdal1h libhdf5-dev libnetcdf-dev cython postgresql-9.4-postgis-2.3 python-pandas python-h5py python-pip python-psycopg2 python-gdal 
  - sudo pip install netCDF4
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension postgis_topology"
  - python bootstrap.py
  - ln -s /usr/bin/psql ./bin/psql
  - ln -s /usr/bin/raster2pgsql ./bin/raster2pgsql
  - ln -s /usr/bin/shp2pgsql ./bin/shp2pgsql
# install
install:
  - ./bin/buildout -c .travis-buildout.cfg
# testing
script:
  - ./bin/rheas -h
after_success:
  - pip install hub-pip==1.1.0
  - python setup.py hub_pip --DeployHubBdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*.jsonld

